/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package fitit;
import com.garmin.fit.*;
import com.github.filosganga.geogson.gson.GeometryAdapterFactory;
import com.github.filosganga.geogson.model.Coordinates;
import com.github.filosganga.geogson.model.Feature;
import com.github.filosganga.geogson.model.Geometry;
import com.github.filosganga.geogson.model.positions.LinearPositions;
import com.github.filosganga.geogson.model.positions.SinglePosition;
import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import spark.Request;
import spark.Response;

import javax.servlet.http.HttpServletResponse;
import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.io.OutputStream;

import static spark.Spark.*;

public class App {

    public static Object getGreeting(Request request, Response response) {
        Gson gson = new GsonBuilder()
                .registerTypeAdapterFactory(new GeometryAdapterFactory())
                .create();
        String gsjon = request.body();


        Gson toTest = new GsonBuilder().registerTypeAdapterFactory(new GeometryAdapterFactory()).create();
        Feature feature = toTest.fromJson(gsjon, Feature.class);


        /*Geometry geometry = new GsonBuilder()
                .registerTypeAdapterFactory(new GeometryAdapterFactory())
                .create()
                .fromJson(gsjon, LineString.class);
         */
        Geometry geometry = feature.geometry();
        BufferEncoder encode;

        try {
            OutputStream out = new ByteArrayOutputStream();
            encode = new BufferEncoder(Fit.ProtocolVersion.V2_0);
        } catch (FitRuntimeException e) {
            System.err.println("Error opening file ExampleActivity.fit");
            return "error";
        }

        //Generate FileIdMessage
        FileIdMesg fileIdMesg = new FileIdMesg(); // Every FIT file MUST contain a 'File ID' message as the first message
        fileIdMesg.setManufacturer(Manufacturer.DEVELOPMENT);
        fileIdMesg.setType(File.COURSE);
        fileIdMesg.setProduct(1);
        fileIdMesg.setSerialNumber(12345L);
        encode.write(fileIdMesg); // Encode the FileIDMesg

        byte[] appId = new byte[]{
                0x1, 0x1, 0x2, 0x3,
                0x5, 0x8, 0xD, 0x15,
                0x22, 0x37, 0x59, (byte) 0x90,
                (byte) 0xE9, 0x79, 0x62, (byte) 0xDB
        };

        DeveloperDataIdMesg developerIdMesg = new DeveloperDataIdMesg();
        for (int i = 0; i < appId.length; i++) {
            developerIdMesg.setApplicationId(i, appId[i]);
        }
        developerIdMesg.setDeveloperDataIndex((short)0);
        encode.write(developerIdMesg);

        CourseMesg courseMesg = new CourseMesg();
        courseMesg.setName("course name");
        courseMesg.setSport(Sport.HIKING);
        encode.write(courseMesg);
        LinearPositions lp = (LinearPositions) geometry.positions();
        for (SinglePosition sp : lp.children()){
            CoursePointMesg cp = new CoursePointMesg();
            Coordinates coordinates = sp.coordinates();
            cp.setPositionLat((int) (coordinates.getLat() * 11930465));
            cp.setPositionLong((int) (coordinates.getLon() * 11930465));
            encode.write(cp);
        }
        try {
            HttpServletResponse raw = response.raw();
            raw.getOutputStream().write(encode.close());
            raw.getOutputStream().flush();
            raw.getOutputStream().close();
            return response.raw();
        } catch (FitRuntimeException | IOException e) {
            System.err.println("Error closing encode.");
            return "error";
        }

    }

    public static void main(String[] args) {
        post("/", (req, res) -> getGreeting(req, res));
    }
}
